// Component catalog data for the dev preview explorer.
// Each entry: { group, name, html, attrs: [[attr, desc], ...] }
// `html` is rendered live and also shown as source.

export const COMPONENTS = [
  // ---------- Layout ----------
  { group: 'Layout', name: 'viewport', html: '<viewport device="web" style="height:160px"><panel padding="16">视口内容</panel></viewport>', attrs: [['device', 'web | ipad | mobile 预设尺寸'], ['width', '显式宽度，覆盖预设'], ['height', '数字固定高度，或 auto']] },
  { group: 'Layout', name: 'layout', html: '<layout columns="1fr 1fr 1fr" gap="12"><panel padding="12">A</panel><panel padding="12">B</panel><panel padding="12">C</panel></layout>', attrs: [['columns', 'CSS grid-template-columns'], ['rows', 'CSS grid-template-rows'], ['gap', '间距 px']] },
  { group: 'Layout', name: 'panel', html: '<panel padding="20" elevation="1">面板内容</panel>', attrs: [['padding', '内边距 px'], ['elevation', '0 | 1 | 2 阴影层级']] },
  { group: 'Layout', name: 'card', html: '<card title="卡片标题" subtitle="副标题" has-footer>正文内容</card>', attrs: [['title', '标题'], ['subtitle', '副标题'], ['has-image', '顶部图片占位'], ['has-footer', '底部操作区']] },
  { group: 'Layout', name: 'split-pane', html: '<split-pane columns="1fr 1fr" style="width:360px"><div>左侧</div><div>右侧</div></split-pane>', attrs: [['columns', '分栏比例']] },
  { group: 'Layout', name: 'divider', html: '上<divider></divider>下', attrs: [['vertical', '竖向分隔']] },
  { group: 'Layout', name: 'navigator', html: '<navigator height="56"><logo></logo><badge count="5"></badge><avatar initials="OC"></avatar></navigator>', attrs: [['height', '高度 px']] },
  { group: 'Layout', name: 'sidebar', html: '<sidebar width="220"><list><list-item label="概览" icon="layout-dashboard" state="selected"></list-item><list-item label="设置" icon="settings"></list-item></list></sidebar>', attrs: [['width', '宽度 px'], ['collapsed', '折叠态']] },
  { group: 'Layout', name: 'logo', html: '<logo label="LOGO" size="100"></logo>', attrs: [['label', '文字'], ['size', '宽度 px']] },

  // ---------- Data input ----------
  { group: 'Data input', name: 'input', html: '<input label="姓名" state="focus" value="张三" icon="user" has-clear-button></input>', attrs: [['state', 'default | focus | filled | error | disabled'], ['label', '标签'], ['value', '值'], ['placeholder', '占位'], ['icon', '前缀图标'], ['has-clear-button', '清除按钮'], ['error', '错误文案'], ['help', '帮助文案']] },
  { group: 'Data input', name: 'search', html: '<search state="filled" value="关键词" has-clear-button></search>', attrs: [['state', '同 input'], ['value', '值'], ['placeholder', '占位']] },
  { group: 'Data input', name: 'textarea', html: '<textarea label="备注" state="filled" rows="3" value="多行文本内容" help="最多 200 字"></textarea>', attrs: [['state', '同 input'], ['rows', '行数'], ['value', '值'], ['label', '标签'], ['error', '错误文案'], ['help', '帮助文案']] },
  { group: 'Data input', name: 'select', html: '<select state="expanded" value="管理员" options="访客,成员,管理员" label="角色"></select>', attrs: [['state', 'collapsed | expanded | filled | error | disabled'], ['value', '当前值'], ['options', '逗号分隔选项'], ['label', '标签'], ['error', '错误文案']] },
  { group: 'Data input', name: 'date-picker', html: '<date-picker state="filled" value="2026-06-08"></date-picker>', attrs: [['state', '同 input'], ['value', '日期值'], ['label', '标签'], ['error', '错误文案']] },
  { group: 'Data input', name: 'checkbox', html: '<checkbox state="checked" label="已选"></checkbox> <checkbox state="error" label="必选未勾"></checkbox>', attrs: [['state', 'unchecked | checked | indeterminate | disabled | error'], ['label', '标签']] },
  { group: 'Data input', name: 'checkbox-group', html: '<checkbox-group label="权限" direction="horizontal" error="至少选择一项"><checkbox state="checked" label="读"></checkbox><checkbox state="checked" label="写"></checkbox><checkbox label="删"></checkbox></checkbox-group>', attrs: [['label', '组标签'], ['direction', 'horizontal | vertical'], ['error', '校验错误']] },
  { group: 'Data input', name: 'radio', html: '<radio state="checked" label="选项 A"></radio>', attrs: [['state', 'unchecked | checked | disabled | error'], ['label', '标签']] },
  { group: 'Data input', name: 'radio-group', html: '<radio-group label="通知方式" error="请选择"><radio state="checked" label="邮件"></radio><radio label="短信"></radio></radio-group>', attrs: [['label', '组标签'], ['direction', 'horizontal | vertical'], ['error', '校验错误']] },
  { group: 'Data input', name: 'toggle', html: '<toggle state="on" label="启用"></toggle> <toggle state="error" label="异常"></toggle>', attrs: [['state', 'on | off | disabled | error'], ['label', '标签']] },
  { group: 'Data input', name: 'password-input', html: '<password-input label="密码" value="secret123" has-show></password-input>', attrs: [['value', '值（掩码显示）'], ['label', '标签'], ['has-show', '显示眼睛'], ['state', '同 input'], ['error', '错误文案']] },
  { group: 'Data input', name: 'tag-input', html: '<tag-input tags="前端,React,设计系统" placeholder="添加标签"></tag-input>', attrs: [['tags', '逗号分隔标签'], ['placeholder', '占位'], ['label', '标签'], ['state', '同 input'], ['error', '错误文案']] },
  { group: 'Data input', name: 'slider', html: '<slider value="60" show-value></slider>', attrs: [['value', '当前值'], ['min', '最小值'], ['max', '最大值'], ['label', '标签'], ['show-value', '显示数值'], ['state', 'default | error | disabled']] },
  { group: 'Data input', name: 'range', html: '<range low="20" high="70"></range>', attrs: [['low', '低端值'], ['high', '高端值'], ['min', '最小值'], ['max', '最大值'], ['state', 'default | error | disabled']] },
  { group: 'Data input', name: 'number-input', html: '<number-input value="42"></number-input>', attrs: [['value', '数值'], ['state', 'default | error | disabled']] },
  { group: 'Data input', name: 'rating', html: '<rating value="3" max="5"></rating>', attrs: [['value', '已选星数'], ['max', '总星数'], ['state', 'default | disabled']] },
  { group: 'Data input', name: 'pin-input', html: '<pin-input length="4" value="12"></pin-input>', attrs: [['length', '位数'], ['value', '已输入值'], ['state', 'default | disabled']] },
  { group: 'Data input', name: 'color-swatch', html: '<color-swatch value="#7c3aed"></color-swatch>', attrs: [['value', '颜色值'], ['label', '显示文字'], ['state', 'default | disabled']] },
  { group: 'Data input', name: 'autocomplete', html: '<autocomplete value="设" open options="设置,设备管理,设计稿" label="搜索"></autocomplete>', attrs: [['value', '输入值'], ['options', '候选项'], ['open', '展开下拉'], ['label', '标签'], ['state', '同 input'], ['error', '错误文案']] },
  { group: 'Data input', name: 'upload', html: '<upload state="uploading" progress="60"></upload>', attrs: [['state', 'empty | has-file | uploading | error'], ['file', '文件名'], ['progress', '上传进度'], ['error', '错误文案']] },
  { group: 'Data input', name: 'button', html: '<button label="主操作" variant="primary" icon="plus"></button> <button label="次要" variant="secondary"></button> <button label="危险" variant="danger"></button>', attrs: [['label', '文字'], ['variant', 'primary | secondary | ghost | danger | link'], ['icon', '图标名'], ['state', 'default | disabled | loading'], ['size', 'sm | md | lg']] },
  { group: 'Data input', name: 'form', html: '<form><form-item label="标题" required><input value="工单标题"></input></form-item><form-item label="描述"><textarea rows="2"></textarea></form-item></form>', attrs: [['layout', 'vertical | horizontal']] },
  { group: 'Data input', name: 'form-item', html: '<form-item label="邮箱" required error="格式不正确"><input state="error" value="bad@"></input></form-item>', attrs: [['label', '标签'], ['required', '必填标记'], ['error', '错误文案']] },

  // ---------- Data display ----------
  { group: 'Data display', name: 'table', html: '<table columns="名称,负责人,状态" has-checkbox has-action><table-row content="RPUI 重构,张三,进行中" checked></table-row><table-row content="登录页改版,李四,已完成"></table-row></table>', attrs: [['rows', '采样行数（无 table-row 子元素时生效）'], ['columns', '逗号分隔列名'], ['has-checkbox', '复选列'], ['has-action', '操作列']] },
  { group: 'Data display', name: 'table-row', html: '<table-row content="A, some, info"></table-row>', attrs: [['content', '逗号分隔单元格'], ['checked', '勾选'], ['state', 'selected 等价 checked']] },
  { group: 'Data display', name: 'table-list-row', html: '<table-list-row content="张三,zhang@example.com,管理员,激活" state="unread"></table-list-row>', attrs: [['content', '逗号分隔单元格'], ['state', 'default | selected | unread | highlighted | disabled']] },
  { group: 'Data display', name: 'chart', html: '<chart kind="bar" data="12,28,18,34,22" labels="Q1,Q2,Q3,Q4,Q5"></chart>', attrs: [['kind', 'bar | line | area | donut | sparkline'], ['data', '逗号分隔数值'], ['labels', '轴标签'], ['height', '高度'], ['color', '主色']] },
  { group: 'Data display', name: 'avatar-group', html: '<avatar-group items="3" overflow="5"></avatar-group>', attrs: [['items', '头像数'], ['overflow', '+N 溢出'], ['size', '尺寸']] },
  { group: 'Data display', name: 'comment', html: '<comment author="张三" avatar="张" time="2 小时前">这块在无权限时应隐藏而非置灰。</comment>', attrs: [['author', '作者'], ['avatar', '缩写'], ['time', '时间'], ['state', 'me 高亮当前用户']] },
  { group: 'Data display', name: 'file-list', html: '<file-list><file-item name="方案.pdf" size="1.2 MB"></file-item><file-item name="截图.png" size="480 KB" state="uploading" progress="60"></file-item><file-item name="数据.xlsx" state="error"></file-item></file-list>', attrs: [['items', '无子元素时自动生成条数']] },
  { group: 'Data display', name: 'file-item', html: '<file-item name="方案.pdf" size="1.2 MB"></file-item>', attrs: [['name', '文件名（决定图标）'], ['size', '大小'], ['state', 'uploaded | uploading | error'], ['progress', '上传进度']] },
  { group: 'Data display', name: 'list', html: '<list><list-item label="收件箱" icon="inbox" badge="12" state="selected"></list-item><list-item label="已归档" icon="archive"></list-item></list>', attrs: [['items', '自动生成条数'], ['state', 'first-selected']] },
  { group: 'Data display', name: 'list-item', html: '<list-item label="消息" icon="message-square" badge="3"></list-item>', attrs: [['label', '文字'], ['icon', '图标名'], ['badge', '角标'], ['state', 'default | selected | disabled']] },
  { group: 'Data display', name: 'tree', html: '<tree><tree-item label="src" icon="folder" expanded level="0"></tree-item><tree-item label="rpui.ts" level="1" state="selected"></tree-item></tree>', attrs: [['(子) tree-item', 'label / icon / level / expanded | collapsed / state']] },
  { group: 'Data display', name: 'timeline', html: '<timeline><timeline-item label="已创建" time="14:00" state="done"></timeline-item><timeline-item label="处理中" time="14:30" state="active"></timeline-item></timeline>', attrs: [['(子) timeline-item', 'label / time / state: default|active|done|error']] },
  { group: 'Data display', name: 'calendar', html: '<calendar month="2026 年 6 月" selected="8"></calendar>', attrs: [['month', '月份标题'], ['selected', '选中日']] },
  { group: 'Data display', name: 'kanban', html: '<kanban><kanban-column title="待办" count="2"><kanban-card label="修复登录" tag="P1"></kanban-card></kanban-column><kanban-column title="进行中" count="1"><kanban-card label="重构"></kanban-card></kanban-column></kanban>', attrs: [['(子) kanban-column', 'title / count'], ['(子) kanban-card', 'label / tag']] },
  { group: 'Data display', name: 'code-block', html: '<code-block lang="typescript" lines="5"></code-block>', attrs: [['lang', '语言标签'], ['lines', '行数']] },
  { group: 'Data display', name: 'diff', html: '<diff rows="5"></diff>', attrs: [['rows', '行数（自动 +/-/上下文）']] },
  { group: 'Data display', name: 'image-grid', html: '<image-grid count="6" columns="3"></image-grid>', attrs: [['count', '图片数'], ['columns', '列数']] },
  { group: 'Data display', name: 'key-value', html: '<key-value><kv-row label="状态" value="进行中"></kv-row><kv-row label="负责人" value="张明"></kv-row></key-value>', attrs: [['(子) kv-row', 'label / value']] },
  { group: 'Data display', name: 'accordion', html: '<accordion><accordion-item label="基本信息" expanded>内容区</accordion-item><accordion-item label="高级设置">折叠内容</accordion-item></accordion>', attrs: [['(子) accordion-item', 'label / expanded']] },
  { group: 'Data display', name: 'stat-card', html: '<stat-card label="活跃用户" value="12,480" trend="up" change="+12%"></stat-card>', attrs: [['label', '指标名'], ['value', '数值'], ['trend', 'up | down | flat'], ['change', '变化文案']] },
  { group: 'Data display', name: 'tag', html: '<tag label="已启用" color="green" closable></tag> <tag label="风险" color="red"></tag>', attrs: [['label', '文字'], ['color', 'green | orange | red'], ['closable', '关闭按钮']] },
  { group: 'Data display', name: 'chip', html: '<chip label="标签" icon="tag" closable></chip>', attrs: [['label', '文字'], ['icon', '图标名'], ['closable', '关闭按钮']] },
  { group: 'Data display', name: 'badge', html: '<badge count="128" max="99"></badge>', attrs: [['count', '数值'], ['max', '上限，超出显示 max+']] },
  { group: 'Data display', name: 'avatar', html: '<avatar size="40" initials="OC"></avatar>', attrs: [['size', '尺寸 px'], ['initials', '首字母']] },
  { group: 'Data display', name: 'image-placeholder', html: '<image-placeholder width="160" height="100" label="封面"></image-placeholder>', attrs: [['width', '宽'], ['height', '高'], ['label', '文字']] },
  { group: 'Data display', name: 'bulk-action-bar', html: '<bulk-action-bar count="3" actions="归档,删除,导出"></bulk-action-bar>', attrs: [['count', '已选数'], ['actions', '逗号分隔动作']] },
  { group: 'Data display', name: 'diagram', html: '<diagram>\ngraph LR\n  A[列表] --> B{有筛选?}\n  B -->|是| C[过滤结果]\n  B -->|否| D[全部数据]\n</diagram>', attrs: [['(文本内容)', 'Mermaid 源码：flowchart / state / sequence / class / ER'], ['(注意)', '图表声明（graph TD 等）需单独成行']] },

  // ---------- Navigation ----------
  { group: 'Navigation', name: 'tabs', html: '<tabs active="1"><tab label="全部" badge="38"></tab><tab label="未读" badge="12"></tab><tab label="已归档"></tab></tabs>', attrs: [['active', '索引或标签'], ['(子) tab', 'label / badge']] },
  { group: 'Navigation', name: 'breadcrumb', html: '<breadcrumb items="工作台,设置,团队"></breadcrumb>', attrs: [['items', '逗号分隔路径']] },
  { group: 'Navigation', name: 'pagination', html: '<pagination total="128" current="2" page-size="20"></pagination>', attrs: [['total', '总数'], ['current', '当前页'], ['page-size', '每页条数']] },
  { group: 'Navigation', name: 'steps', html: '<steps steps="填写信息,分配角色,完成" active="1"></steps>', attrs: [['steps', '逗号分隔步骤'], ['active', '当前步索引']] },
  { group: 'Navigation', name: 'segmented', html: '<segmented options="日,周,月" active="1"></segmented>', attrs: [['options', '逗号分隔'], ['active', '索引或标签']] },
  { group: 'Navigation', name: 'menu', html: '<menu><menu-item label="打开" icon="folder" shortcut="⌘O"></menu-item><menu-item label="删除" icon="trash-2" shortcut="⌫"></menu-item></menu>', attrs: [['(子) menu-item', 'label / icon / shortcut / state']] },
  { group: 'Navigation', name: 'context-menu', html: '<context-menu items="复制,重命名,移动到,删除"></context-menu>', attrs: [['items', '逗号分隔（含「删除」自动标红）']] },
  { group: 'Navigation', name: 'command-palette', html: '<command-palette query="" results="新建文件,打开设置,搜索工单,切换主题"></command-palette>', attrs: [['query', '当前输入'], ['results', '逗号分隔结果']] },
  { group: 'Navigation', name: 'toc', html: '<toc items="概述,安装,用法,API"></toc>', attrs: [['items', '逗号分隔目录项']] },
  { group: 'Navigation', name: 'kbd', html: '<kbd keys="⌘,K"></kbd>', attrs: [['keys', '逗号分隔按键']] },
  { group: 'Navigation', name: 'anchor', html: '<anchor to="payment.rpml" label="去支付页"></anchor> <anchor to="payment.rpml" section="2" label="支付页·方式" icon="external-link"></anchor>', attrs: [['to', '目标 .rpml 路径（同一文件集内）'], ['section', '可选，目标页要聚焦的注释 id'], ['label', '链接文字'], ['icon', '图标名，默认 arrow-right']] },

  // ---------- Feedback ----------
  { group: 'Feedback', name: 'alert', html: '<alert type="warning" title="SLA 风险" message="1 小时内未响应将升级" closable></alert>', attrs: [['type', 'info | success | warning | error'], ['title', '标题'], ['message', '正文'], ['closable', '关闭按钮']] },
  { group: 'Feedback', name: 'toast', html: '<toast type="success" title="已保存"></toast>', attrs: [['type', '同 alert'], ['title', '标题'], ['message', '正文']] },
  { group: 'Feedback', name: 'banner', html: '<banner type="warning" title="维护通知" message="今晚 22:00 例行维护" closable></banner>', attrs: [['type', '同 alert'], ['title', '标题'], ['message', '正文'], ['has-action', '操作按钮'], ['closable', '关闭']] },
  { group: 'Feedback', name: 'empty', html: '<empty label="暂无数据" description="创建后显示在这里" has-action></empty>', attrs: [['label', '主文案'], ['description', '说明'], ['has-action', '操作按钮']] },
  { group: 'Feedback', name: 'loading', html: '<loading rows="4"></loading>', attrs: [['kind', 'skeleton | spinner'], ['rows', '骨架行数']] },
  { group: 'Feedback', name: 'skeleton', html: '<skeleton shape="card"></skeleton>', attrs: [['shape', 'line | block | card | list | avatar']] },
  { group: 'Feedback', name: 'progress', html: '<progress value="64"></progress>', attrs: [['value', '0-100'], ['kind', 'bar | circle'], ['status', 'success | error']] },
  { group: 'Feedback', name: 'countdown', html: '<countdown value="02:45:18"></countdown>', attrs: [['value', '剩余时间文案']] },
  { group: 'Feedback', name: 'result', html: '<result status="success" title="提交成功" description="我们会尽快处理" has-action></result>', attrs: [['status', 'success | error | empty'], ['title', '标题'], ['description', '说明'], ['has-action', '操作按钮']] },

  // ---------- Overlays ----------
  { group: 'Overlays', name: 'modal', html: '<modal title="确认操作" has-footer><alert type="warning" title="不可恢复" message="请确认后继续"></alert></modal>', attrs: [['title', '标题'], ['width', '宽度'], ['has-footer', '底部按钮']] },
  { group: 'Overlays', name: 'drawer', html: '<drawer title="详情" width="320"><form><form-item label="名称"><input value="张三"></input></form-item></form></drawer>', attrs: [['title', '标题'], ['width', '宽度'], ['side', 'left | right']] },
  { group: 'Overlays', name: 'dropdown', html: '<dropdown title="菜单"><list-item label="编辑" icon="edit"></list-item><list-item label="删除" icon="trash-2"></list-item></dropdown>', attrs: [['title', '标题'], ['width', '宽度']] },
  { group: 'Overlays', name: 'popover', html: '<popover title="提示">弹出内容</popover>', attrs: [['title', '标题'], ['width', '宽度']] },
  { group: 'Overlays', name: 'tooltip', html: '<tooltip text="提示气泡"></tooltip>', attrs: [['text', '文字'], ['position', 'top | bottom | left | right']] },

  // ---------- Enterprise ----------
  { group: 'Enterprise', name: 'permission-gate', html: '<permission-gate reason="需管理员权限"><button label="删除组织" variant="danger"></button></permission-gate>', attrs: [['reason', '锁定原因']] },
  { group: 'Enterprise', name: 'quota-bar', html: '<quota-bar label="API 调用" used="920" limit="1000"></quota-bar>', attrs: [['label', '标签'], ['used', '已用'], ['limit', '上限（≥90% 标红）']] },
  { group: 'Enterprise', name: 'api-key', html: '<api-key value="sk_live_••••••••3f9a"></api-key>', attrs: [['value', '掩码后的密钥']] },
  { group: 'Enterprise', name: 'audit-row', html: '<audit-row actor="张明" action="将工单标记为已解决" time="2 分钟前"></audit-row>', attrs: [['actor', '操作者'], ['action', '动作描述'], ['time', '时间']] },
  { group: 'Enterprise', name: 'workflow-node', html: '<workflow-node label="审批" state="active"></workflow-node>', attrs: [['label', '节点名'], ['state', 'default | active | done | error']] },

  // ---------- iOS ----------
  { group: 'iOS', name: 'ios-navbar', html: '<ios-navbar title="消息" large back="返回" trailing="编辑"></ios-navbar>', attrs: [['title', '标题'], ['large', '大标题'], ['back', '返回文字'], ['trailing', '右侧文字']] },
  { group: 'iOS', name: 'ios-tabbar', html: '<ios-tabbar items="主页,搜索,通知,我的" icons="home,search,bell,user" active="0"></ios-tabbar>', attrs: [['items', '逗号分隔'], ['icons', '逗号分隔图标'], ['active', '索引']] },
  { group: 'iOS', name: 'ios-list', html: '<ios-list header="账户"><ios-list-item label="Apple ID" detail="zhang@me.com" icon="user" chevron></ios-list-item><ios-list-item label="通知" icon="bell" chevron></ios-list-item></ios-list>', attrs: [['header', '分组标题'], ['(子) ios-list-item', 'label / detail / icon / chevron']] },
  { group: 'iOS', name: 'ios-action-sheet', html: '<ios-action-sheet title="选择来源" actions="拍照,从相册选择,浏览文件" destructive="删除"></ios-action-sheet>', attrs: [['title', '标题'], ['actions', '逗号分隔'], ['destructive', '标红的动作']] },
  { group: 'iOS', name: 'ios-alert', html: '<ios-alert title="删除会话？" message="此操作无法撤销" actions="取消,删除"></ios-alert>', attrs: [['title', '标题'], ['message', '正文'], ['actions', '逗号分隔按钮']] },
  { group: 'iOS', name: 'ios-switch', html: '<ios-switch label="Wi-Fi"></ios-switch>', attrs: [['label', '标签'], ['state', 'on | off']] },
  { group: 'iOS', name: 'ios-segmented', html: '<ios-segmented options="全部,未读,提及" active="0"></ios-segmented>', attrs: [['options', '逗号分隔'], ['active', '索引']] },
  { group: 'iOS', name: 'ios-button', html: '<ios-button label="继续"></ios-button> <ios-button label="淡色" variant="tinted"></ios-button>', attrs: [['label', '文字'], ['variant', 'filled | tinted | plain']] },
  { group: 'iOS', name: 'ios-search', html: '<ios-search placeholder="搜索"></ios-search>', attrs: [['value', '值'], ['placeholder', '占位']] },
  { group: 'iOS', name: 'ios-stepper', html: '<ios-stepper></ios-stepper>', attrs: [['value', '数值']] },

  // ---------- macOS ----------
  { group: 'macOS', name: 'macos-window', html: '<macos-window title="访达"><macos-toolbar><macos-segmented options="图标,列表,分栏" active="1"></macos-segmented></macos-toolbar><macos-table columns="名称,大小" rows="4"></macos-table></macos-window>', attrs: [['title', '窗口标题']] },
  { group: 'macOS', name: 'macos-menubar', html: '<macos-menubar items="文件,编辑,显示,窗口,帮助"></macos-menubar>', attrs: [['items', '逗号分隔菜单']] },
  { group: 'macOS', name: 'macos-toolbar', html: '<macos-toolbar><macos-segmented options="A,B,C" active="0"></macos-segmented></macos-toolbar>', attrs: [['(slot)', '放入工具项']] },
  { group: 'macOS', name: 'macos-sidebar', html: '<macos-sidebar><macos-source-item group label="收藏夹"></macos-source-item><macos-source-item label="最近使用" icon="clock" state="selected"></macos-source-item><macos-source-item label="下载" icon="download"></macos-source-item></macos-sidebar>', attrs: [['(子) macos-source-item', 'label / icon / group / state']] },
  { group: 'macOS', name: 'macos-segmented', html: '<macos-segmented options="全部,未读,标记" active="0"></macos-segmented>', attrs: [['options', '逗号分隔'], ['active', '索引']] },
  { group: 'macOS', name: 'macos-popover', html: '<macos-popover title="快速操作"><macos-stepper></macos-stepper></macos-popover>', attrs: [['title', '标题']] },
  { group: 'macOS', name: 'macos-sheet', html: '<macos-sheet title="导出文档"><key-value><kv-row label="格式" value="PDF"></kv-row></key-value></macos-sheet>', attrs: [['title', '标题']] },
  { group: 'macOS', name: 'macos-disclosure', html: '<macos-disclosure label="高级选项" expanded>展开内容</macos-disclosure>', attrs: [['label', '标签'], ['expanded', '展开态']] },
  { group: 'macOS', name: 'macos-stepper', html: '<macos-stepper></macos-stepper>', attrs: [['value', '数值']] },
  { group: 'macOS', name: 'macos-table', html: '<macos-table columns="名称,修改日期,大小" rows="5"></macos-table>', attrs: [['columns', '逗号分隔列名'], ['rows', '行数']] },

  // ---------- Agent / 对话式 UI ----------
  { group: 'Agent UI', name: 'chat', html: '<chat><user-message text="帮我查一下登录失败的工单"></user-message><agent-message text="找到 3 条相关工单，最近一条是 #TK-20593。"></agent-message></chat>', attrs: [['(容器)', '包裹 user/agent message 等对话内容']] },
  { group: 'Agent UI', name: 'user-message', html: '<user-message text="帮我总结这份报告的要点" initials="我"></user-message>', attrs: [['text', '消息文本（或放入子元素）'], ['initials', '头像首字母']] },
  { group: 'Agent UI', name: 'agent-message', html: '<agent-message name="Agent" text="好的，报告共有三个要点……"></agent-message>', attrs: [['name', '角色名（默认 Agent）'], ['text', '文本（或放入富文本子元素）']] },
  { group: 'Agent UI', name: 'system-message', html: '<system-message text="已切换到 GPT-5 模型"></system-message>', attrs: [['text', '系统提示文本']] },
  { group: 'Agent UI', name: 'tool-call', html: '<tool-call name="search_tickets" state="done" args="query=登录失败, limit=5"></tool-call>', attrs: [['name', '工具名称（直接展示为标题）'], ['state', 'running | done | error'], ['args', '参数（独立一行展示，非方法调用）']] },
  { group: 'Agent UI', name: 'agent-output', html: '<agent-output kind="terminal" label="终端输出" text="$ npm run build\\n✓ built in 111ms"></agent-output>', attrs: [['kind', 'text | code | terminal'], ['label', '标题'], ['text', '输出内容（或子元素）']] },
  { group: 'Agent UI', name: 'reasoning', html: '<reasoning expanded>先定位工单状态机，再筛选 SLA 超时项……</reasoning>', attrs: [['expanded', '展开思考内容']] },
  { group: 'Agent UI', name: 'message-actions', html: '<message-actions actions="copy,retry,up,down"></message-actions>', attrs: [['actions', 'copy,retry,up,down,edit,share']] },
  { group: 'Agent UI', name: 'suggestions', html: '<suggestions items="总结要点,继续,给个例子"></suggestions>', attrs: [['items', '逗号分隔的建议回复']] },
  { group: 'Agent UI', name: 'typing', html: '<typing></typing>', attrs: [['(无)', '流式输入中的三点指示器']] },
  { group: 'Agent UI', name: 'composer', html: '<composer value="分析这份数据" modes="thinking,web" files="报告.pdf,数据.xlsx" model="GPT-4o" state="idle"></composer>', attrs: [['value', '输入值'], ['placeholder', '占位'], ['state', 'idle | streaming | disabled'], ['modes', '激活的开关：thinking | web | code'], ['files', '附件列表'], ['model', '模型名胶囊']] },
  { group: 'Agent UI', name: 'citation', html: '<citation index="1" title="工单 #TK-20593 处理记录"></citation>', attrs: [['index', '编号'], ['title', '来源标题']] },
  { group: 'Agent UI', name: 'token-usage', html: '<token-usage used="1840" limit="8000"></token-usage>', attrs: [['used', '已用 token'], ['limit', '上限']] },
];

