import { define } from './core/dom';
import { RpAnnotation, RpEnum, RpEnumItem } from './canvas/annotation';
import { RpMainView } from './canvas/main-view';
import { RpPage } from './canvas/page';
import { GenericElement, LayoutElement, LogoElement, NavbarElement, PanelElement, SidebarElement, ViewportElement } from './primitives/layout';
import { ButtonElement, CheckboxElement, DatePickerElement, FieldElement, FormElement, FormItemElement, ImagePlaceholderElement, ProgressElement, RadioElement, SelectElement, TextareaElement, ToggleElement, UploadElement } from './primitives/controls';
import { AvatarElement, BadgeElement, BreadcrumbElement, ListElement, ListItemElement, PaginationElement, StepsElement, TabElement, TabsElement } from './primitives/navigation';
import { AlertElement, BulkActionBarElement, CardElement, DrawerElement, EmptyElement, LoadingElement, ModalElement, OverlayElement, StatCardElement, TableElement, TableRowElement, TagElement, TooltipElement } from './primitives/data-display';

export function registerAll() { define('rp-page', RpPage); define('proto-page', RpPage); define('rp-main-view', RpMainView); define('proto-main-view', RpMainView); define('rp-annotation', RpAnnotation); define('proto-annotation', RpAnnotation); define('rp-enum', RpEnum); define('proto-enum', RpEnum); define('rp-enum-item', RpEnumItem); define('proto-enum-item', RpEnumItem); const pairs: Array<[string, CustomElementConstructor]> = [ ['viewport', ViewportElement], ['layout', LayoutElement], ['panel', PanelElement], ['navbar', NavbarElement], ['sidebar', SidebarElement], ['logo', LogoElement], ['search', FieldElement], ['input', FieldElement], ['textarea', TextareaElement], ['select', SelectElement], ['badge', BadgeElement], ['avatar', AvatarElement], ['list', ListElement], ['list-item', ListItemElement], ['tabs', TabsElement], ['tab', TabElement], ['button', ButtonElement], ['button-group', GenericElement], ['table', TableElement], ['table-row', TableRowElement], ['bulk-action-bar', BulkActionBarElement], ['empty', EmptyElement], ['loading', LoadingElement], ['alert', AlertElement], ['toast', AlertElement], ['dropdown', OverlayElement], ['popover', OverlayElement], ['tooltip', TooltipElement], ['modal', ModalElement], ['drawer', DrawerElement], ['card', CardElement], ['stat-card', StatCardElement], ['tag', TagElement], ['checkbox', CheckboxElement], ['radio', RadioElement], ['toggle', ToggleElement], ['form', FormElement], ['form-item', FormItemElement], ['date-picker', DatePickerElement], ['upload', UploadElement], ['image-placeholder', ImagePlaceholderElement], ['progress', ProgressElement], ['pagination', PaginationElement], ['steps', StepsElement], ['breadcrumb', BreadcrumbElement] ]; for (const [suffix, ctor] of pairs) { define(`snap-${suffix}`, ctor); define(`rp-${suffix}`, ctor); } }


