import { injectStyle } from '../core/style';
import { attr, csv, escapeHtml } from '../core/dom';
import { icon } from '../core/icons';

export class FieldElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const value = attr(this,'value'); const placeholder = attr(this,'placeholder','Search'); const label = attr(this,'label'); const error = attr(this,'error-message'); const showValue = value || attr(this,'state') === 'filled'; const content = `${this.fieldIcon()}<span class="${showValue ? 'rp-value' : 'rp-placeholder'}">${escapeHtml(value || placeholder)}</span>${this.hasAttribute('has-clear-button') ? icon('x',14) : ''}`; this.innerHTML = label || error ? `<span class="rp-field-label">${escapeHtml(label)}</span><span class="rp-field-control">${content}</span>${error ? `<span class="rp-error-text">${escapeHtml(error)}</span>` : ''}` : content; } fieldIcon() { return icon(this.tagName.toLowerCase().includes('date-picker') ? 'calendar' : 'search'); } }
export class TextareaElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady = 'true'; this.style.setProperty('--snap-rows', attr(this,'rows','3')); const value = attr(this,'value') || attr(this,'placeholder','Textarea'); this.innerHTML = `<span class="${attr(this,'value') ? 'rp-value' : 'rp-placeholder'}">${escapeHtml(value)}</span>`; } }
export class SelectElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady = 'true'; const options = csv(this, 'options', '选项 A,选项 B,选项 C'); const value = attr(this, 'value', options[0] || 'Select'); const label = attr(this, 'label'); this.innerHTML = `${label ? `<span class="rp-field-label">${escapeHtml(label)}</span>` : ''}<span class="rp-select-control"><span class="rp-select-value">${escapeHtml(value)}</span>${icon('chevron-down')}</span><span class="rp-select-options">${options.map(o => `<span class="rp-select-option${o === value ? ' selected' : ''}">${escapeHtml(o)}</span>`).join('')}</span>`; } }
export class ButtonElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const label = attr(this,'label', this.textContent?.trim() || 'Button'); const ic = attr(this,'icon'); const loading = attr(this,'state') === 'loading'; this.innerHTML = `${loading ? icon('loader') : ic ? icon(ic) : ''}<span>${escapeHtml(label)}</span>`; } }
export class CheckboxElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const state = attr(this,'state'); const mark = state === 'checked' ? icon('check',12) : state === 'indeterminate' ? icon('minus',12) : ''; this.innerHTML = `<span class="rp-box">${mark}</span><span>${escapeHtml(attr(this,'label',''))}</span>`; } }
export class RadioElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const checked = attr(this,'state') === 'checked'; this.innerHTML = `<span class="rp-box">${checked ? icon('circle',8) : ''}</span><span>${escapeHtml(attr(this,'label',''))}</span>`; } }
export class ToggleElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; this.innerHTML = `<span class="rp-toggle-track"><span class="rp-toggle-dot"></span></span><span>${escapeHtml(attr(this,'label',''))}</span>`; } }
export class FormElement extends HTMLElement { connectedCallback() { injectStyle(); } }
export class FormItemElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady = 'true'; const children = Array.from(this.childNodes); const label = attr(this,'label'); const error = attr(this,'error'); this.innerHTML = `${label ? `<span class="rp-form-label${this.hasAttribute('required') ? ' required' : ''}">${escapeHtml(label)}</span>` : ''}`; children.forEach(n => this.appendChild(n)); if (error) this.insertAdjacentHTML('beforeend', `<span class="rp-form-error">${escapeHtml(error)}</span>`); } }
export class DatePickerElement extends FieldElement { fieldIcon() { return icon('calendar'); } }
export class UploadElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady = 'true'; const state = attr(this,'state','empty'); if (state === 'has-file') this.innerHTML = `${icon('file')}<span>${escapeHtml(attr(this,'file','document.pdf'))}</span>`; else if (state === 'uploading') this.innerHTML = `${icon('loader')}<span>上传中...</span><span class="rp-progress-bar" style="width:${escapeHtml(attr(this,'progress','60'))}%"></span>`; else this.innerHTML = `${icon('upload',24)}<span>${escapeHtml(attr(this,'label','点击或拖拽文件上传'))}</span>`; } }
export class ImagePlaceholderElement extends HTMLElement { connectedCallback() { injectStyle(); this.style.setProperty('--snap-width', `${attr(this,'width','160')}px`); this.style.setProperty('--snap-height', `${attr(this,'height','100')}px`); if (!this.innerHTML.trim()) this.innerHTML = `${icon('image')} ${escapeHtml(attr(this,'label','Image'))}`; } }
export class ProgressElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const value = attr(this,'value','40'); this.style.setProperty('--progress', `${value}%`); const kind = attr(this,'kind', attr(this,'style')); this.innerHTML = kind === 'circle' ? `${escapeHtml(value)}%` : '<span class="rp-progress-bar"></span>'; } }

