import { injectStyle } from '../core/style';
import { attr, csv, escapeHtml, intAttr } from '../core/dom';
import { icon } from '../core/icons';

export function sampleCell(c:string, j:number, i:number) { const lower = c.toLowerCase(); if (c.includes('发件') || lower.includes('name')) return ['张三','李四','系统通知','运营助手','王五','安全团队'][i%6]; if (c.includes('预览') || lower.includes('preview')) return ['请确认新的项目评审时间','本周周报已发送','你的账号存在新的登录','活动报名已通过审核','附件已更新','安全策略变更提醒'][i%6]; if (c.includes('时间') || lower.includes('time')) return ['09:12','昨天','周二','5月30日','5月28日','5月20日'][i%6]; if (c.includes('状态') || lower.includes('status')) return i % 2 ? '未读' : '已读'; return `Data ${i+1}-${j+1}`; }
export class TableElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const cols = csv(this,'columns','Name,Preview,Time,Status'); const rows = intAttr(this,'rows',4); const hasCheckbox = this.hasAttribute('has-checkbox'); const hasAction = this.hasAttribute('has-action'); const finalCols = hasAction ? [...cols, '操作'] : cols; const headCells = `${hasCheckbox ? '<span class="rp-table-cell">✓</span>' : ''}${finalCols.map(c=>`<span class="rp-table-cell">${escapeHtml(c)}</span>`).join('')}`; const body = Array.from({length: rows}, (_,i) => `<div class="rp-table-row">${hasCheckbox ? `<span class="rp-table-cell"><span class="rp-box">${i===1 ? icon('check',12) : ''}</span></span>` : ''}${finalCols.map((c,j)=>`<span class="rp-table-cell">${c === '操作' ? '<snap-button label="查看" variant="link"></snap-button>' : escapeHtml(sampleCell(c,j,i))}</span>`).join('')}</div>`).join(''); this.innerHTML = `<div class="rp-table-row rp-table-head">${headCells}</div>${body}`; } }
export class TableRowElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; this.innerHTML = `<span><span class="rp-box">${attr(this,'state')==='selected'?icon('check',12):''}</span></span><span>张三</span><span>消息内容预览文本</span><span>09:12</span><span>${escapeHtml(attr(this,'state','default'))}</span>`; } }
export class BulkActionBarElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const count = attr(this,'count','1'); const actions = csv(this,'actions','确认,取消'); this.innerHTML = `${icon('check')}<span>已选 ${escapeHtml(count)} 项</span>${actions.map(a=>`<snap-button label="${escapeHtml(a)}" variant="ghost"></snap-button>`).join('')}`; } }
export class EmptyElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; this.innerHTML = `${icon('empty',28)}<span class="rp-empty-title">${escapeHtml(attr(this,'label','暂无数据'))}</span><span class="rp-empty-desc">${escapeHtml(attr(this,'description',''))}</span>${this.hasAttribute('has-action') ? '<snap-button label="新建" variant="primary" icon="plus"></snap-button>' : ''}`; } }
export class LoadingElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const rows = intAttr(this,'rows',3); this.innerHTML = attr(this,'kind') === 'spinner' || attr(this,'style') === 'spinner' ? `<span class="rp-spinner">${icon('loader',24)}</span>` : Array.from({length: rows}, (_,i)=>`<span class="rp-skeleton-line" style="width:${220 - i*24}px"></span>`).join(''); } }
export class AlertElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const type = attr(this,'type','info'); const title = attr(this,'title', type === 'error' ? '错误' : '提示'); const message = attr(this,'message',''); const ic = type === 'error' ? 'circle-alert' : type === 'warning' ? 'alert-triangle' : type === 'success' ? 'circle-check' : 'info'; this.innerHTML = `${icon(ic)}<span><strong>${escapeHtml(title)}</strong>${message ? `<br>${escapeHtml(message)}` : ''}</span>${this.hasAttribute('closable') ? icon('x',14) : ''}`; } }
export class OverlayElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady = 'true'; const children = Array.from(this.childNodes); const title = attr(this,'title'); if (!title) return; const head = document.createElement('div'); head.className = 'rp-overlay-title'; head.textContent = title; this.prepend(head); children.forEach(n => this.appendChild(n)); } }
export class TooltipElement extends HTMLElement { connectedCallback() { injectStyle(); if (!this.textContent?.trim()) this.textContent = attr(this,'text','提示内容'); } }
export class ModalElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady = 'true'; this.style.setProperty('--snap-width', `${attr(this,'width','480')}px`); const children = Array.from(this.childNodes); const body = document.createElement('div'); body.className = 'rp-modal-body'; children.forEach(n => body.appendChild(n)); this.innerHTML = `<div class="rp-modal-head"><span>${escapeHtml(attr(this,'title','标题'))}</span>${icon('x',14)}</div>`; this.appendChild(body); if (this.hasAttribute('has-footer')) this.insertAdjacentHTML('beforeend', '<div class="rp-modal-footer"><snap-button label="取消"></snap-button><snap-button label="确认" variant="primary"></snap-button></div>'); } }
export class DrawerElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady = 'true'; this.style.setProperty('--snap-width', `${attr(this,'width','360')}px`); const children = Array.from(this.childNodes); const body = document.createElement('div'); body.className = 'rp-drawer-body'; children.forEach(n => body.appendChild(n)); this.innerHTML = `<div class="rp-drawer-head"><span>${escapeHtml(attr(this,'title','抽屉'))}</span>${icon('x',14)}</div>`; this.appendChild(body); } }
export class CardElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady = 'true'; const children = Array.from(this.childNodes); const title = attr(this,'title'); const subtitle = attr(this,'subtitle'); this.innerHTML = `${this.hasAttribute('has-image') ? `<span class="rp-card-image">${icon('image')} Image</span>` : ''}${title ? `<span class="rp-card-title">${escapeHtml(title)}</span>` : ''}${subtitle ? `<span class="rp-card-subtitle">${escapeHtml(subtitle)}</span>` : ''}`; children.forEach(n => this.appendChild(n)); if (this.hasAttribute('has-footer')) this.insertAdjacentHTML('beforeend', '<span class="rp-card-footer"><snap-button label="查看" variant="secondary"></snap-button></span>'); } }
export class StatCardElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady = 'true'; this.innerHTML = `<span class="rp-stat-label">${escapeHtml(attr(this,'label','指标'))}</span><span class="rp-stat-value">${escapeHtml(attr(this,'value','128'))}</span><span class="rp-stat-change">${escapeHtml(attr(this,'change','0%'))}</span>`; } }
export class TagElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady = 'true'; const label = attr(this,'label', this.textContent?.trim() || 'Tag'); this.innerHTML = `<span>${escapeHtml(label)}</span>${this.hasAttribute('closable') ? icon('x',12) : ''}`; } }

export class ChipElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const label = attr(this,'label', this.textContent?.trim() || 'Chip'); const ic = attr(this,'icon'); this.innerHTML = `${ic ? icon(ic,12) : ''}<span>${escapeHtml(label)}</span>${this.hasAttribute('closable') ? icon('x',11) : ''}`; } }
export class TreeElement extends HTMLElement { connectedCallback() { injectStyle(); } }
export class TreeItemElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const level = intAttr(this,'level',0); const label = attr(this,'label','Node'); const ic = attr(this,'icon'); const expandable = this.hasAttribute('expanded') || this.hasAttribute('collapsed'); const expanded = this.hasAttribute('expanded'); const caret = expandable ? icon(expanded ? 'chevron-down' : 'chevron-right',12) : '<span class="rp-tree-spacer"></span>'; this.style.setProperty('--tree-level', String(level)); this.innerHTML = `<span class="rp-tree-row${attr(this,'state')==='selected' ? ' selected' : ''}">${caret}${icon(ic || (expandable ? 'folder' : 'file'),14)}<span class="rp-tree-label">${escapeHtml(label)}</span></span>`; } }
export class TimelineElement extends HTMLElement { connectedCallback() { injectStyle(); } }
export class TimelineItemElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const children = Array.from(this.childNodes); const label = attr(this,'label'); const time = attr(this,'time'); const state = attr(this,'state','default'); const dot = `<span class="rp-timeline-dot ${state}"></span>`; const head = `<div class="rp-timeline-head"><span class="rp-timeline-label">${escapeHtml(label)}</span>${time ? `<span class="rp-timeline-time">${escapeHtml(time)}</span>` : ''}</div>`; const body = document.createElement('div'); body.className = 'rp-timeline-content'; children.forEach(n=>body.appendChild(n)); this.innerHTML = `${dot}<div class="rp-timeline-main">${head}</div>`; this.querySelector('.rp-timeline-main')!.appendChild(body); } }
export class CalendarElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const month = attr(this,'month','2026 年 6 月'); const selected = intAttr(this,'selected',15); const dows = ['一','二','三','四','五','六','日']; const cells = Array.from({length:35},(_,i)=>{ const day = i - 1; const valid = day >= 1 && day <= 30; return `<span class="rp-cal-cell${valid && day===selected ? ' selected' : ''}${valid ? '' : ' muted'}">${valid ? day : ''}</span>`; }).join(''); this.innerHTML = `<div class="rp-cal-head"><span>${escapeHtml(month)}</span></div><div class="rp-cal-grid">${dows.map(d=>`<span class="rp-cal-dow">${d}</span>`).join('')}${cells}</div>`; } }
export class KanbanElement extends HTMLElement { connectedCallback() { injectStyle(); } }
export class KanbanColumnElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const children = Array.from(this.childNodes); const title = attr(this,'title','列'); const count = attr(this,'count'); const head = document.createElement('div'); head.className = 'rp-kanban-head'; head.innerHTML = `<span>${escapeHtml(title)}</span>${count ? `<span class="rp-kanban-count">${escapeHtml(count)}</span>` : ''}`; const body = document.createElement('div'); body.className = 'rp-kanban-body'; children.forEach(n=>body.appendChild(n)); this.append(head, body); } }
export class KanbanCardElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const label = attr(this,'label','卡片'); const tag = attr(this,'tag'); this.innerHTML = `<span class="rp-kanban-card-title">${escapeHtml(label)}</span>${tag ? `<span class="rp-kanban-card-tag">${escapeHtml(tag)}</span>` : ''}`; } }
export class CodeBlockElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const lines = intAttr(this,'lines',5); const lang = attr(this,'lang','ts'); const body = Array.from({length:lines},(_,i)=>`<span class="rp-code-line"><span class="rp-code-ln">${i+1}</span><span class="rp-code-bar" style="width:${40 + ((i*37)%50)}%"></span></span>`).join(''); this.innerHTML = `<div class="rp-code-head">${escapeHtml(lang)}</div><div class="rp-code-body">${body}</div>`; } }
export class DiffElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const rows = intAttr(this,'rows',4); const body = Array.from({length:rows},(_,i)=>{ const kind = i%3===0 ? 'add' : i%3===1 ? 'del' : 'ctx'; const sign = kind==='add'?'+':kind==='del'?'-':' '; return `<span class="rp-diff-line ${kind}"><span class="rp-diff-sign">${sign}</span><span class="rp-code-bar" style="width:${45+((i*29)%45)}%"></span></span>`; }).join(''); this.innerHTML = body; } }
export class ImageGridElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const count = intAttr(this,'count',6); const cols = intAttr(this,'columns',3); this.style.setProperty('--grid-cols', String(cols)); this.innerHTML = Array.from({length:count},()=>`<span class="rp-grid-cell">${icon('image',20)}</span>`).join(''); } }
export class KeyValueElement extends HTMLElement { connectedCallback() { injectStyle(); } }
export class KvRowElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; this.innerHTML = `<span class="rp-kv-key">${escapeHtml(attr(this,'label','键'))}</span><span class="rp-kv-val">${escapeHtml(attr(this,'value','值'))}</span>`; } }
export class AccordionElement extends HTMLElement { connectedCallback() { injectStyle(); } }
export class AccordionItemElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const children = Array.from(this.childNodes); const label = attr(this,'label','分节'); const expanded = this.hasAttribute('expanded'); const head = document.createElement('div'); head.className = 'rp-accordion-head'; head.innerHTML = `${icon(expanded ? 'chevron-down' : 'chevron-right',14)}<span>${escapeHtml(label)}</span>`; this.appendChild(head); if (expanded) { const body = document.createElement('div'); body.className = 'rp-accordion-body'; children.forEach(n=>body.appendChild(n)); this.appendChild(body); } } }
export class BannerElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const type = attr(this,'type','info'); const ic = type==='error'?'circle-alert':type==='warning'?'alert-triangle':type==='success'?'circle-check':'info'; this.innerHTML = `${icon(ic)}<span class="rp-banner-text"><strong>${escapeHtml(attr(this,'title','通知'))}</strong>${attr(this,'message') ? ` ${escapeHtml(attr(this,'message'))}` : ''}</span>${this.hasAttribute('has-action') ? '<snap-button label="查看" variant="link"></snap-button>' : ''}${this.hasAttribute('closable') ? icon('x',14) : ''}`; } }
export class SkeletonElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const shape = attr(this,'shape','line'); if (shape==='avatar') this.innerHTML = '<span class="rp-skel rp-skel-avatar"></span>'; else if (shape==='card') this.innerHTML = '<span class="rp-skel rp-skel-block"></span><span class="rp-skeleton-line" style="width:70%"></span><span class="rp-skeleton-line" style="width:50%"></span>'; else if (shape==='list') this.innerHTML = Array.from({length:3},()=>'<span class="rp-skel-row"><span class="rp-skel rp-skel-avatar sm"></span><span class="rp-skeleton-line" style="width:60%"></span></span>').join(''); else this.innerHTML = '<span class="rp-skeleton-line"></span>'; } }
export class CountdownElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; this.innerHTML = `${icon('clock',13)}<span>${escapeHtml(attr(this,'value','02:45:18'))}</span>`; } }
export class ResultElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const status = attr(this,'status','success'); const ic = status==='error'?'circle-x':status==='empty'?'empty':'circle-check'; this.innerHTML = `<span class="rp-result-icon ${status}">${icon(ic,40)}</span><span class="rp-result-title">${escapeHtml(attr(this,'title','操作成功'))}</span><span class="rp-result-desc">${escapeHtml(attr(this,'description',''))}</span>${this.hasAttribute('has-action') ? '<snap-button label="返回" variant="primary"></snap-button>' : ''}`; } }
export class PermissionGateElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const children = Array.from(this.childNodes); const wrap = document.createElement('div'); wrap.className = 'rp-gate-content'; children.forEach(n=>wrap.appendChild(n)); const overlay = document.createElement('div'); overlay.className = 'rp-gate-overlay'; overlay.innerHTML = `${icon('lock',16)}<span>${escapeHtml(attr(this,'reason','无权限'))}</span>`; this.append(wrap, overlay); } }
export class QuotaBarElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const used = intAttr(this,'used',70); const limit = intAttr(this,'limit',100); const pct = limit ? Math.min(100,(used/limit)*100) : 0; const danger = pct >= 90; this.innerHTML = `<div class="rp-quota-head"><span>${escapeHtml(attr(this,'label','用量'))}</span><span class="rp-quota-num${danger ? ' danger' : ''}">${used} / ${limit}</span></div><span class="rp-quota-track"><span class="rp-quota-fill${danger ? ' danger' : ''}" style="width:${pct}%"></span></span>`; } }
export class ApiKeyElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const value = attr(this,'value','sk_live_••••••••••••3f9a'); this.innerHTML = `<span class="rp-apikey-val">${escapeHtml(value)}</span><span class="rp-apikey-copy">${icon('copy',14)}</span>`; } }
export class AuditRowElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; this.innerHTML = `<span class="rp-audit-actor">${escapeHtml(attr(this,'actor','用户'))}</span><span class="rp-audit-action">${escapeHtml(attr(this,'action','执行了操作'))}</span><span class="rp-audit-time">${escapeHtml(attr(this,'time','刚刚'))}</span>`; } }
export class WorkflowNodeElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const state = attr(this,'state','default'); const ic = state==='done'?'circle-check':state==='active'?'circle':state==='error'?'circle-x':'circle'; this.innerHTML = `<span class="rp-wf-icon ${state}">${icon(ic,16)}</span><span class="rp-wf-label">${escapeHtml(attr(this,'label','节点'))}</span>`; } }

