import { injectStyle } from '../core/style';
import { attr, csv, escapeHtml, intAttr } from '../core/dom';
import { icon } from '../core/icons';

export function sampleCell(c:string, j:number, i:number) { const lower = c.toLowerCase(); if (c.includes('发件') || lower.includes('name')) return ['张三','李四','系统通知','运营助手','王五','安全团队'][i%6]; if (c.includes('预览') || lower.includes('preview')) return ['请确认新的项目评审时间','本周周报已发送','你的账号存在新的登录','活动报名已通过审核','附件已更新','安全策略变更提醒'][i%6]; if (c.includes('时间') || lower.includes('time')) return ['09:12','昨天','周二','5月30日','5月28日','5月20日'][i%6]; if (c.includes('状态') || lower.includes('status')) return i % 2 ? '未读' : '已读'; return `Data ${i+1}-${j+1}`; }
export class TableElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const cols = csv(this,'columns','Name,Preview,Time,Status'); const rows = intAttr(this,'rows',4); const hasCheckbox = this.hasAttribute('has-checkbox'); const hasAction = this.hasAttribute('has-action'); const finalCols = hasAction ? [...cols, '操作'] : cols; const headCells = `${hasCheckbox ? '<span class="rp-table-cell">✓</span>' : ''}${finalCols.map(c=>`<span class="rp-table-cell">${escapeHtml(c)}</span>`).join('')}`; const body = Array.from({length: rows}, (_,i) => `<div class="rp-table-row">${hasCheckbox ? `<span class="rp-table-cell"><span class="rp-box">${i===1 ? icon('check',12) : ''}</span></span>` : ''}${finalCols.map((c,j)=>`<span class="rp-table-cell">${c === '操作' ? '<snap-button label="查看" variant="link"></snap-button>' : escapeHtml(sampleCell(c,j,i))}</span>`).join('')}</div>`).join(''); this.innerHTML = `<div class="rp-table-row rp-table-head">${headCells}</div>${body}`; } }
export class TableRowElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; this.innerHTML = `<span><span class="rp-box">${attr(this,'state')==='selected'?icon('check',12):''}</span></span><span>张三</span><span>消息内容预览文本</span><span>09:12</span><span>${escapeHtml(attr(this,'state','default'))}</span>`; } }
export class BulkActionBarElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const count = attr(this,'count','1'); const actions = csv(this,'actions','确认,取消'); this.innerHTML = `${icon('check')}<span>已选 ${escapeHtml(count)} 项</span>${actions.map(a=>`<snap-button label="${escapeHtml(a)}" variant="ghost"></snap-button>`).join('')}`; } }
export class EmptyElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; this.innerHTML = `${icon('empty',28)}<span class="rp-empty-title">${escapeHtml(attr(this,'label','暂无数据'))}</span><span class="rp-empty-desc">${escapeHtml(attr(this,'description',''))}</span>${this.hasAttribute('has-action') ? '<snap-button label="新建" variant="primary" icon="plus"></snap-button>' : ''}`; } }
export class LoadingElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const rows = intAttr(this,'rows',3); this.innerHTML = attr(this,'kind') === 'spinner' || attr(this,'style') === 'spinner' ? `<span class="rp-spinner">${icon('loader',24)}</span>` : Array.from({length: rows}, (_,i)=>`<span class="rp-skeleton-line" style="width:${220 - i*24}px"></span>`).join(''); } }
export class AlertElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const type = attr(this,'type','info'); const title = attr(this,'title', type === 'error' ? '错误' : '提示'); const message = attr(this,'message',''); const ic = type === 'error' ? 'circle-alert' : type === 'warning' ? 'alert-triangle' : type === 'success' ? 'circle-check' : 'info'; this.innerHTML = `${icon(ic)}<span><strong>${escapeHtml(title)}</strong>${message ? `<br>${escapeHtml(message)}` : ''}</span>${this.hasAttribute('closable') ? icon('x',14) : ''}`; } }
export class OverlayElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady = 'true'; const children = Array.from(this.childNodes); const title = attr(this,'title'); if (!title) return; const head = document.createElement('div'); head.className = 'rp-overlay-title'; head.textContent = title; this.prepend(head); children.forEach(n => this.appendChild(n)); } }
export class TooltipElement extends HTMLElement { connectedCallback() { injectStyle(); if (!this.textContent?.trim()) this.textContent = attr(this,'text','提示内容'); } }
export class ModalElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady = 'true'; this.style.setProperty('--snap-width', `${attr(this,'width','480')}px`); const children = Array.from(this.childNodes); const body = document.createElement('div'); body.className = 'rp-modal-body'; children.forEach(n => body.appendChild(n)); this.innerHTML = `<div class="rp-modal-head"><span>${escapeHtml(attr(this,'title','标题'))}</span>${icon('x',14)}</div>`; this.appendChild(body); if (this.hasAttribute('has-footer')) this.insertAdjacentHTML('beforeend', '<div class="rp-modal-footer"><snap-button label="取消"></snap-button><snap-button label="确认" variant="primary"></snap-button></div>'); } }
export class DrawerElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady = 'true'; this.style.setProperty('--snap-width', `${attr(this,'width','360')}px`); const children = Array.from(this.childNodes); const body = document.createElement('div'); body.className = 'rp-drawer-body'; children.forEach(n => body.appendChild(n)); this.innerHTML = `<div class="rp-drawer-head"><span>${escapeHtml(attr(this,'title','抽屉'))}</span>${icon('x',14)}</div>`; this.appendChild(body); } }
export class CardElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady = 'true'; const children = Array.from(this.childNodes); const title = attr(this,'title'); const subtitle = attr(this,'subtitle'); this.innerHTML = `${this.hasAttribute('has-image') ? `<span class="rp-card-image">${icon('image')} Image</span>` : ''}${title ? `<span class="rp-card-title">${escapeHtml(title)}</span>` : ''}${subtitle ? `<span class="rp-card-subtitle">${escapeHtml(subtitle)}</span>` : ''}`; children.forEach(n => this.appendChild(n)); if (this.hasAttribute('has-footer')) this.insertAdjacentHTML('beforeend', '<span class="rp-card-footer"><snap-button label="查看" variant="secondary"></snap-button></span>'); } }
export class StatCardElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady = 'true'; this.innerHTML = `<span class="rp-stat-label">${escapeHtml(attr(this,'label','指标'))}</span><span class="rp-stat-value">${escapeHtml(attr(this,'value','128'))}</span><span class="rp-stat-change">${escapeHtml(attr(this,'change','0%'))}</span>`; } }
export class TagElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady = 'true'; const label = attr(this,'label', this.textContent?.trim() || 'Tag'); this.innerHTML = `<span>${escapeHtml(label)}</span>${this.hasAttribute('closable') ? icon('x',12) : ''}`; } }

