import { injectStyle } from '../core/style';
import { attr, csv, escapeHtml, intAttr } from '../core/dom';
import { icon } from '../core/icons';

// iOS (Apple HIG) platform primitives. Static visual approximations only.
export class IosNavbarElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const title = attr(this,'title','标题'); const large = this.hasAttribute('large'); const back = attr(this,'back'); const trailing = attr(this,'trailing'); this.innerHTML = `<div class="rp-ios-navbar-row"><span class="rp-ios-nav-leading">${back ? `${icon('chevron-left',18)}<span>${escapeHtml(back)}</span>` : ''}</span><span class="rp-ios-nav-title${large ? ' inline' : ''}">${large ? '' : escapeHtml(title)}</span><span class="rp-ios-nav-trailing">${trailing ? escapeHtml(trailing) : ''}</span></div>${large ? `<div class="rp-ios-nav-large">${escapeHtml(title)}</div>` : ''}`; } }
export class IosTabbarElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const items = csv(this,'items','首页,搜索,通知,我的'); const icons = csv(this,'icons','home,search,bell,user'); const active = intAttr(this,'active',0); this.innerHTML = items.map((it,i)=>`<span class="rp-ios-tab${i===active?' active':''}">${icon(icons[i] || 'circle',22)}<span class="rp-ios-tab-label">${escapeHtml(it)}</span></span>`).join(''); } }
export class IosListElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const header = attr(this,'header'); if (header) { const h = document.createElement('div'); h.className = 'rp-ios-list-header'; h.textContent = header; this.insertBefore(h, this.firstChild); } } }
export class IosListItemElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const label = attr(this,'label','项'); const detail = attr(this,'detail'); const ic = attr(this,'icon'); const chevron = this.hasAttribute('chevron'); this.innerHTML = `${ic ? `<span class="rp-ios-li-icon">${icon(ic,16)}</span>` : ''}<span class="rp-ios-li-label">${escapeHtml(label)}</span>${detail ? `<span class="rp-ios-li-detail">${escapeHtml(detail)}</span>` : ''}${chevron ? `<span class="rp-ios-li-chevron">${icon('chevron-right',16)}</span>` : ''}`; } }
export class IosActionSheetElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const title = attr(this,'title'); const actions = csv(this,'actions','拍照,从相册选择,选择文件'); const destructive = attr(this,'destructive'); const group = `<div class="rp-ios-as-group">${title ? `<div class="rp-ios-as-title">${escapeHtml(title)}</div>` : ''}${actions.map(a=>`<div class="rp-ios-as-action${a===destructive?' destructive':''}">${escapeHtml(a)}</div>`).join('')}</div>`; const cancel = `<div class="rp-ios-as-group"><div class="rp-ios-as-action cancel">取消</div></div>`; this.innerHTML = group + cancel; } }
export class IosAlertElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const title = attr(this,'title','提示'); const message = attr(this,'message',''); const actions = csv(this,'actions','取消,确定'); this.innerHTML = `<div class="rp-ios-alert-body"><div class="rp-ios-alert-title">${escapeHtml(title)}</div>${message ? `<div class="rp-ios-alert-msg">${escapeHtml(message)}</div>` : ''}</div><div class="rp-ios-alert-actions">${actions.map((a,i)=>`<span class="rp-ios-alert-btn${i===actions.length-1?' primary':''}">${escapeHtml(a)}</span>`).join('')}</div>`; } }
export class IosSwitchElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const label = attr(this,'label'); this.innerHTML = `${label ? `<span class="rp-ios-switch-label">${escapeHtml(label)}</span>` : ''}<span class="rp-ios-switch-track"><span class="rp-ios-switch-dot"></span></span>`; } }
export class IosSegmentedElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const options = csv(this,'options','第一,第二,第三'); const active = intAttr(this,'active',0); this.innerHTML = options.map((o,i)=>`<span class="rp-ios-seg-item${i===active?' active':''}">${escapeHtml(o)}</span>`).join(''); } }
export class IosButtonElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; this.innerHTML = `<span>${escapeHtml(attr(this,'label', this.textContent?.trim() || '按钮'))}</span>`; } }
export class IosSearchElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const value = attr(this,'value'); this.innerHTML = `${icon('search',15)}<span class="${value ? 'rp-value' : 'rp-placeholder'}">${escapeHtml(value || attr(this,'placeholder','搜索'))}</span>`; } }
export class IosStepperElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; this.innerHTML = `<span class="rp-ios-step minus">${icon('minus',16)}</span><span class="rp-ios-step-div"></span><span class="rp-ios-step plus">${icon('plus',16)}</span>`; } }
