import { injectStyle } from '../core/style';
import { attr, csv, intAttr, escapeHtml } from '../core/dom';
import { icon } from '../core/icons';

export class BadgeElement extends HTMLElement { connectedCallback() { injectStyle(); const count = attr(this,'count','0'); const max = intAttr(this,'max',99); const n = Number(count); this.textContent = Number.isFinite(n) && n > max ? `${max}+` : count; } }
export class AvatarElement extends HTMLElement { connectedCallback() { injectStyle(); const size = attr(this,'size','32'); this.style.setProperty('--snap-size', `${size}px`); if (!this.textContent?.trim()) this.textContent = attr(this,'initials','U'); } }
export class ListElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady || this.children.length) return; this.dataset.rpReady='true'; const items = intAttr(this,'items',3); const state = attr(this,'state'); this.innerHTML = Array.from({length: items}, (_,i)=>`<snap-list-item label="${['全部','未读','@ 我','已归档','设置'][i] || `Item ${i+1}`}" icon="${['inbox','message-square','at-sign','archive','settings'][i] || 'file'}"${state === 'first-selected' && i === 0 ? ' state="selected"' : ''}></snap-list-item>`).join(''); } }
export class ListItemElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const label = attr(this,'label', this.textContent?.trim() || 'Item'); const badge = attr(this,'badge'); const ic = attr(this,'icon'); this.innerHTML = `${ic ? icon(ic) : ''}<span class="rp-list-label">${escapeHtml(label)}</span>${badge ? `<span class="rp-list-badge">${escapeHtml(badge)}</span>` : ''}`; } }
export class TabsElement extends HTMLElement { connectedCallback() { injectStyle(); const active = attr(this,'active','0'); const numeric = Number(active); const children = Array.from(this.children) as HTMLElement[]; children.forEach((child, i) => { const label = child.getAttribute('label') || child.textContent?.trim() || ''; const isActive = Number.isFinite(numeric) ? i === numeric : label === active; child.classList.toggle('rp-tab-active', isActive); }); } }
export class TabElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const label = attr(this,'label', this.textContent?.trim() || 'Tab'); const badge = attr(this,'badge'); this.innerHTML = `<span>${escapeHtml(label)}</span>${badge ? `<span class="rp-list-badge">${escapeHtml(badge)}</span>` : ''}`; } }
export class PaginationElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady = 'true'; const total = intAttr(this,'total',10); const current = intAttr(this,'current',1); const pageSize = intAttr(this,'page-size',10); const pages = Math.max(1, Math.ceil(total / pageSize)); const visible = Array.from({length: Math.min(pages,5)}, (_,i)=>i+1); this.innerHTML = `<span class="rp-page-btn">${icon('chevron-left',14)}</span>${visible.map(p=>`<span class="rp-page-btn${p===current?' active':''}">${p}</span>`).join('')}<span class="rp-page-btn">${icon('chevron-right',14)}</span><span>共 ${total} 条</span>`; } }
export class StepsElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady = 'true'; const steps = csv(this,'steps','步骤一,步骤二,步骤三'); const active = intAttr(this,'active',0); this.innerHTML = steps.map((s,i)=>`<span class="rp-step ${i < active ? 'done' : i === active ? 'active' : ''}"><span class="rp-step-dot">${i < active ? icon('check',12) : i + 1}</span>${escapeHtml(s)}</span>${i < steps.length - 1 ? '<span class="rp-step-sep"></span>' : ''}`).join(''); } }
export class BreadcrumbElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady = 'true'; const items = csv(this,'items','首页,当前页'); this.innerHTML = items.map((item,i)=>`<span class="${i===items.length-1?'rp-breadcrumb-current':''}">${escapeHtml(item)}</span>${i < items.length - 1 ? '<span>/</span>' : ''}`).join(''); } }


