import { injectStyle } from '../core/style';
import { attr, csv, escapeHtml, intAttr } from '../core/dom';
import { icon } from '../core/icons';

export class FieldElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const value = attr(this,'value'); const placeholder = attr(this,'placeholder','Search'); const label = attr(this,'label'); const error = attr(this,'error') || attr(this,'error-message'); const help = attr(this,'help'); const showValue = value || attr(this,'state') === 'filled'; const content = `${this.fieldIcon()}<span class="${showValue ? 'rp-value' : 'rp-placeholder'}">${escapeHtml(value || placeholder)}</span>${this.hasAttribute('has-clear-button') ? `<span class="rp-field-clear">${icon('x',14)}</span>` : ''}`; if (label || error || help) { this.classList.add('rp-field-group'); this.innerHTML = `<span class="rp-field-label">${escapeHtml(label)}</span><span class="rp-field-control">${content}</span>${help ? `<span class="rp-field-help">${escapeHtml(help)}</span>` : ''}${error ? `<span class="rp-error-text">${escapeHtml(error)}</span>` : ''}`; } else { this.innerHTML = content; } } fieldIcon() { const tag = this.tagName.toLowerCase(); if (tag === 'search-el') return icon('search'); const ic = attr(this,'icon'); return ic ? icon(ic, 15) : ''; } }
export class TextareaElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady = 'true'; this.style.setProperty('--snap-rows', attr(this,'rows','3')); const value = attr(this,'value'); const placeholder = attr(this,'placeholder','Textarea'); const label = attr(this,'label'); const error = attr(this,'error') || attr(this,'error-message'); const help = attr(this,'help'); const inner = `<span class="${value ? 'rp-value' : 'rp-placeholder'}">${escapeHtml(value || placeholder)}</span>`; if (label || error || help) { this.classList.add('rp-field-group'); this.innerHTML = `<span class="rp-field-label">${escapeHtml(label)}</span><span class="rp-field-control">${inner}</span>${help ? `<span class="rp-field-help">${escapeHtml(help)}</span>` : ''}${error ? `<span class="rp-error-text">${escapeHtml(error)}</span>` : ''}`; } else { this.innerHTML = inner; } } }
export class SelectElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const options = csv(this, 'options', '选项 A,选项 B,选项 C'); const value = attr(this, 'value', options[0] || 'Select'); const label = attr(this, 'label'); const error = attr(this, 'error') || attr(this, 'error-message'); this.innerHTML = `${label ? `<span class="rp-field-label">${escapeHtml(label)}</span>` : ''}<span class="select-el-control"><span class="select-el-value">${escapeHtml(value)}</span>${icon('chevron-down')}</span><span class="select-el-options">${options.map(o => `<span class="select-el-option${o === value ? ' selected' : ''}">${escapeHtml(o)}</span>`).join('')}</span>${error ? `<span class="rp-error-text">${escapeHtml(error)}</span>` : ''}`; } }
export class ButtonElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const label = attr(this,'label', this.textContent?.trim() || 'Button'); const ic = attr(this,'icon'); const loading = attr(this,'state') === 'loading'; this.innerHTML = `${loading ? icon('loader') : ic ? icon(ic) : ''}<span>${escapeHtml(label)}</span>`; } }
export class CheckboxElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const state = attr(this,'state'); const mark = state === 'checked' ? icon('check',12) : state === 'indeterminate' ? icon('minus',12) : ''; this.innerHTML = `<span class="rp-box">${mark}</span><span>${escapeHtml(attr(this,'label',''))}</span>`; } }
export class RadioElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const checked = attr(this,'state') === 'checked'; this.innerHTML = `<span class="rp-box">${checked ? icon('circle',8) : ''}</span><span>${escapeHtml(attr(this,'label',''))}</span>`; } }
export class ToggleElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; this.innerHTML = `<span class="toggle-el-track"><span class="toggle-el-dot"></span></span><span>${escapeHtml(attr(this,'label',''))}</span>`; } }
export class FormElement extends HTMLElement { connectedCallback() { injectStyle(); } }
export class FormItemElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady = 'true'; const children = Array.from(this.childNodes); const label = attr(this,'label'); const error = attr(this,'error'); this.innerHTML = `${label ? `<span class="form-el-label${this.hasAttribute('required') ? ' required' : ''}">${escapeHtml(label)}</span>` : ''}`; children.forEach(n => this.appendChild(n)); if (error) this.insertAdjacentHTML('beforeend', `<span class="form-el-error">${escapeHtml(error)}</span>`); } }
export class DatePickerElement extends FieldElement { fieldIcon() { return icon('calendar'); } }
export class UploadElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady = 'true'; const state = attr(this,'state','empty'); if (state === 'has-file') this.innerHTML = `${icon('file')}<span>${escapeHtml(attr(this,'file','document.pdf'))}</span>`; else if (state === 'uploading') this.innerHTML = `${icon('loader')}<span>上传中...</span><span class="progress-el-bar" style="width:${escapeHtml(attr(this,'progress','60'))}%"></span>`; else if (state === 'error') this.innerHTML = `${icon('circle-x',24)}<span>${escapeHtml(attr(this,'error') || attr(this,'label') || '上传失败，点击重试')}</span>`; else this.innerHTML = `${icon('upload',24)}<span>${escapeHtml(attr(this,'label','点击或拖拽文件上传'))}</span>`; } }
export class ImagePlaceholderElement extends HTMLElement { connectedCallback() { injectStyle(); this.style.setProperty('--snap-width', `${attr(this,'width','160')}px`); this.style.setProperty('--snap-height', `${attr(this,'height','100')}px`); if (!this.innerHTML.trim()) this.innerHTML = `${icon('image')} ${escapeHtml(attr(this,'label','Image'))}`; } }
export class ProgressElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const value = attr(this,'value','40'); this.style.setProperty('--progress', `${value}%`); const kind = attr(this,'kind', attr(this,'style')); this.innerHTML = kind === 'circle' ? `${escapeHtml(value)}%` : '<span class="progress-el-bar"></span>'; } }

export class SliderElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const min = intAttr(this,'min',0); const max = intAttr(this,'max',100); const value = intAttr(this,'value',40); const pct = max > min ? Math.max(0, Math.min(100, ((value - min) / (max - min)) * 100)) : 0; const label = attr(this,'label'); this.innerHTML = `${label ? `<span class="rp-field-label">${escapeHtml(label)}</span>` : ''}<span class="slider-el-track"><span class="slider-el-fill" style="width:${pct}%"></span><span class="slider-el-thumb" style="left:${pct}%"></span></span>${this.hasAttribute('show-value') ? `<span class="slider-el-value">${value}</span>` : ''}`; } }
export class RangeElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const min = intAttr(this,'min',0); const max = intAttr(this,'max',100); const low = intAttr(this,'low',25); const high = intAttr(this,'high',75); const span = max - min || 1; const l = ((low - min) / span) * 100; const h = ((high - min) / span) * 100; this.innerHTML = `<span class="slider-el-track"><span class="slider-el-fill" style="left:${l}%;width:${h - l}%"></span><span class="slider-el-thumb" style="left:${l}%"></span><span class="slider-el-thumb" style="left:${h}%"></span></span>`; } }
export class NumberInputElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const value = attr(this,'value','0'); this.innerHTML = `<span class="rp-num-value">${escapeHtml(value)}</span><span class="rp-num-steppers"><span class="rp-num-step">${icon('chevron-up',12)}</span><span class="rp-num-step">${icon('chevron-down',12)}</span></span>`; } }
export class RatingElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const max = intAttr(this,'max',5); const value = intAttr(this,'value',3); this.innerHTML = Array.from({length:max},(_,i)=>`<span class="rp-star${i < value ? ' filled' : ''}">${icon('star',16)}</span>`).join(''); } }
export class PinInputElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const len = intAttr(this,'length',4); const value = attr(this,'value',''); const chars = value.split(''); this.innerHTML = Array.from({length:len},(_,i)=>`<span class="rp-pin-cell${i === chars.length ? ' active' : ''}">${escapeHtml(chars[i] || '')}</span>`).join(''); } }
export class ColorSwatchElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const value = attr(this,'value','#2563eb'); this.innerHTML = `<span class="rp-swatch-chip" style="background:${escapeHtml(value)}"></span><span class="rp-swatch-hex">${escapeHtml(attr(this,'label', value))}</span>`; } }
export class AutocompleteElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const value = attr(this,'value'); const options = csv(this,'options','选项一,选项二,选项三'); const label = attr(this,'label'); const error = attr(this,'error') || attr(this,'error-message'); this.innerHTML = `${label ? `<span class="rp-field-label">${escapeHtml(label)}</span>` : ''}<span class="rp-field-control">${icon('search')}<span class="${value ? 'rp-value' : 'rp-placeholder'}">${escapeHtml(value || attr(this,'placeholder','输入以搜索'))}</span></span>${this.hasAttribute('open') ? `<span class="rp-ac-options">${options.map(o=>`<span class="rp-ac-option">${escapeHtml(o)}</span>`).join('')}</span>` : ''}${error ? `<span class="rp-error-text">${escapeHtml(error)}</span>` : ''}`; } }

export class PasswordInputElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const value = attr(this,'value'); const placeholder = attr(this,'placeholder','请输入密码'); const label = attr(this,'label'); const error = attr(this,'error') || attr(this,'error-message'); const help = attr(this,'help'); const masked = value ? '•'.repeat(Math.min(12, value.length)) : ''; const inner = `<span class="${value ? 'rp-value' : 'rp-placeholder'}">${escapeHtml(masked || placeholder)}</span>${this.hasAttribute('has-show') ? `<span class="rp-field-clear">${icon('eye',15)}</span>` : ''}`; this.innerHTML = `${label ? `<span class="rp-field-label">${escapeHtml(label)}</span>` : ''}<span class="rp-field-control">${inner}</span>${help ? `<span class="rp-field-help">${escapeHtml(help)}</span>` : ''}${error ? `<span class="rp-error-text">${escapeHtml(error)}</span>` : ''}`; } }
export class TagInputElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const tags = csv(this,'tags',''); const placeholder = attr(this,'placeholder','输入后回车添加'); const label = attr(this,'label'); const error = attr(this,'error') || attr(this,'error-message'); const chips = tags.map(t => `<span class="rp-taginput-chip">${escapeHtml(t)}${icon('x',11)}</span>`).join(''); const inner = `${chips}<span class="rp-placeholder">${escapeHtml(placeholder)}</span>`; this.innerHTML = `${label ? `<span class="rp-field-label">${escapeHtml(label)}</span>` : ''}<span class="rp-field-control rp-taginput">${inner}</span>${error ? `<span class="rp-error-text">${escapeHtml(error)}</span>` : ''}`; } }
export class ChoiceGroupElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const label = attr(this,'label'); const error = attr(this,'error') || attr(this,'error-message'); if (attr(this,'direction') === 'horizontal') this.classList.add('rp-group-h'); if (label) this.insertAdjacentHTML('afterbegin', `<span class="rp-group-label">${escapeHtml(label)}</span>`); if (error) this.insertAdjacentHTML('beforeend', `<span class="rp-error-text">${escapeHtml(error)}</span>`); } }

