import { injectStyle } from '../core/style';
import { attr, csv, escapeHtml, intAttr } from '../core/dom';
import { icon } from '../core/icons';

// macOS (Apple HIG) platform primitives. Static visual approximations only.
export class MacWindowElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const children = Array.from(this.childNodes); const title = attr(this,'title','窗口'); const titlebar = `<div class="rp-mac-titlebar"><span class="rp-mac-lights"><span class="rp-mac-light close"></span><span class="rp-mac-light min"></span><span class="rp-mac-light max"></span></span><span class="rp-mac-title">${escapeHtml(title)}</span></div>`; const body = document.createElement('div'); body.className = 'rp-mac-window-body'; children.forEach(n=>body.appendChild(n)); this.innerHTML = titlebar; this.appendChild(body); } }
export class MacToolbarElement extends HTMLElement { connectedCallback() { injectStyle(); } }
export class MacMenubarElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const items = csv(this,'items','文件,编辑,显示,窗口,帮助'); this.innerHTML = `<span class="rp-mac-menubar-apple">${icon('home',14)}</span>` + items.map((it,i)=>`<span class="rp-mac-menu-title${i===0?' active':''}">${escapeHtml(it)}</span>`).join(''); } }
export class MacSidebarElement extends HTMLElement { connectedCallback() { injectStyle(); } }
export class MacSourceItemElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const label = attr(this,'label','项'); const ic = attr(this,'icon'); if (this.hasAttribute('group')) { this.classList.add('rp-mac-source-group'); this.textContent = label; return; } this.innerHTML = `${ic ? icon(ic,15) : ''}<span class="rp-mac-source-label">${escapeHtml(label)}</span>`; if (attr(this,'state')==='selected') this.classList.add('selected'); } }
export class MacSegmentedElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const options = csv(this,'options','全部,未读,标记'); const active = intAttr(this,'active',0); this.innerHTML = options.map((o,i)=>`<span class="rp-mac-seg-item${i===active?' active':''}">${escapeHtml(o)}</span>`).join(''); } }
export class MacPopoverElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const children = Array.from(this.childNodes); const title = attr(this,'title'); const arrow = '<span class="rp-mac-pop-arrow"></span>'; const body = document.createElement('div'); body.className = 'rp-mac-pop-body'; if (title) { const h = document.createElement('div'); h.className='rp-mac-pop-title'; h.textContent = title; body.appendChild(h); } children.forEach(n=>body.appendChild(n)); this.innerHTML = arrow; this.appendChild(body); } }
export class MacSheetElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const children = Array.from(this.childNodes); const title = attr(this,'title','操作'); const body = document.createElement('div'); body.className = 'rp-mac-sheet-body'; children.forEach(n=>body.appendChild(n)); this.innerHTML = `<div class="rp-mac-sheet-title">${escapeHtml(title)}</div>`; this.appendChild(body); this.insertAdjacentHTML('beforeend','<div class="rp-mac-sheet-actions"><snap-button label="取消"></snap-button><snap-button label="完成" variant="primary"></snap-button></div>'); } }
export class MacStepperElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; this.innerHTML = `<span class="rp-mac-step up">${icon('chevron-up',11)}</span><span class="rp-mac-step down">${icon('chevron-down',11)}</span>`; } }
export class MacDisclosureElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const children = Array.from(this.childNodes); const label = attr(this,'label','详情'); const expanded = this.hasAttribute('expanded'); const head = document.createElement('div'); head.className = 'rp-mac-disc-head'; head.innerHTML = `<span class="rp-mac-disc-tri${expanded?' open':''}">${icon('chevron-right',12)}</span><span>${escapeHtml(label)}</span>`; this.appendChild(head); if (expanded) { const body = document.createElement('div'); body.className='rp-mac-disc-body'; children.forEach(n=>body.appendChild(n)); this.appendChild(body); } } }
export class MacTableElement extends HTMLElement { connectedCallback() { injectStyle(); if (this.dataset.rpReady) return; this.dataset.rpReady='true'; const cols = csv(this,'columns','名称,类型,大小'); const rows = intAttr(this,'rows',5); const head = `<div class="rp-mac-tr rp-mac-th">${cols.map((c,i)=>`<span class="rp-mac-td">${escapeHtml(c)}${i===0?icon('chevron-up',10):''}</span>`).join('')}</div>`; const body = Array.from({length:rows},(_,r)=>`<div class="rp-mac-tr${r%2?' alt':''}">${cols.map((c,ci)=>`<span class="rp-mac-td">${ci===0?icon('file',13):''}<span class="rp-mac-cell-bar" style="width:${50+((r*17+ci*23)%40)}%"></span></span>`).join('')}</div>`).join(''); this.innerHTML = head + body; } }
